resources:
  pipelines:
    - pipeline: dotnet-monitor
      source: dotnet-dotnet-monitor
      trigger:
        branches:
          include:
          - release/*
          - internal/release/*
        tags:
        - update-docker
trigger: none
pr: none
schedules:
- cron: "0 13 * * Mon-Fri"
  displayName: M-F daily build
  branches:
    include:
    - nightly
  always: true
parameters:
- name: usePipelineResource
  displayName: 'Use dotnet-monitor pipeline resource?'
  type: boolean
  default: false
variables:
- template: ../common/templates/variables/dotnet/common.yml
stages:
- stage: Monitor
  jobs:
  - job: UpdateDependencies
    displayName: Update Dependencies (dotnet/dotnet-monitor)
    pool:
      vmImage: $(defaultLinuxAmd64PoolImage)
    steps:
    - ${{ if or(eq(parameters.usePipelineResource, true), eq(variables['Build.Reason'], 'ResourceTrigger')) }}:
      - download: dotnet-monitor
        artifact: buildversion
        displayName: "Download Build Version (Branch: $(resources.pipeline.dotnet-monitor.sourceBranch))"
      - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -BuildVersionFilePath "$(Pipeline.Workspace)/dotnet-monitor/buildversion/buildversion"
        displayName: Get Versions (Resource Trigger)
    - ${{ else }}:
      - pwsh: $(engPath)/Get-MonitorDropVersions.ps1 -Channel $(MajorMinorVersion)/$(ChannelQuality)
        displayName: Get Versions

    - powershell: |
        $customArgs = "$(monitorMajorMinorVersion) --product-version monitor=$(monitorVer) --version-source-name dotnet/dotnet-monitor/$(monitorMajorMinorVersion) --stable-branding=$(stableBranding)"

        $customArgsArray = @($customArgs)
        echo "##vso[task.setvariable variable=customArgsArray]$($customArgsArray | ConvertTo-Json -Compress -AsArray)"
      displayName: Set Custom Args
    - template: steps/update-dependencies.yml
      parameters:
        customArgsArray: $(customArgsArray)
